AWSTemplateFormatVersion: 2010-09-09

Description: Create EC2 instances which are target of provisioning by Ansible

Parameters:
  YourPrivateKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: your-private-key
  YourSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-1234abcd
  YourImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-06cd52961ce9f0d85 # Amazon Linux AMI 2018.03.0 (HVM), SSD Volume Type

Resources:
  ApplicationServer:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-northeast-1a
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 50 # GiB
      ImageId: !Ref YourImageId
      InstanceType: t2.micro
      KeyName: !Ref YourPrivateKeyName
      SecurityGroupIds:
        - !Ref YourSecurityGroupId
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-northeast-1a
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20 # GiB
      ImageId: !Ref YourImageId
      InstanceType: t2.micro
      KeyName: !Ref YourPrivateKeyName
      SecurityGroupIds:
        - !Ref YourSecurityGroupId

Outputs:
  PrivateKeyName:
    Description: This key is required to login as ec2-user.
    Value: !Ref YourPrivateKeyName

  ApplicationServerPublicIP:
    Description: This address must be set to ApplicationServer group in Ansible inventory file.
    Value: !GetAtt [ApplicationServer, PublicIp]
  WebServerPublicIP:
    Description: This address must be set to WebServer group in Ansible inventory file.
    Value: !GetAtt [WebServer, PublicIp]
